import 'package:flutter/widgets.dart';

class AppLanguage {
  static final ValueNotifier<Locale> localeNotifier = ValueNotifier(const Locale('mr'));

  static void changeLocale(Locale locale) {
    localeNotifier.value = locale;
  }
}

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('en'),
    Locale('mr'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final localizations = Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(localizations != null, 'AppLocalizations not found in context');
    return localizations!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Revolve Agro',
      'language': 'Language',
      'english': 'English',
      'marathi': 'Marathi',
      'grow_smarter_title': 'Grow smarter,\nGrow healthier.',  
      'grow_smarter_subtitle':
          'Discover crop care products, place orders faster, and manage your farm purchases in one polished flow.',
      'trusted_products': 'Trusted Products',
      'easy_checkout': 'Easy Checkout',
      'continue': 'Continue',
      'loading_app': 'Loading App...',
      'splash_tagline': 'Smart farming starts here',
      'browse_products_directly': 'Browse Products Directly',
      'choose_experience_title': 'Choose your\nexperience',
      'choose_experience_subtitle':
          'Farmers and admins get tailored dashboards, faster actions, and a smoother purchase journey.',
      'user_login': 'User Login',
      'admin_login': 'Admin Login',
      'super_admin_login': 'Super Admin Login',
      'user_login_subtitle': 'Browse products, manage your cart, and checkout with delivery details.',
      'admin_login_subtitle': 'Track incoming orders, customer addresses, and overall order activity.',
      'super_admin_login_subtitle': 'Manage all admin functionalities and system-wide settings.',

      'multilingual_support':
          'Available for multilingual agriculture support and faster team coordination.',
      'startup_hint': 'We are preparing your account, products, and settings in the background.',
      'admin_workspace': 'Admin Workspace',
      'farmer_workspace': 'Farmer Workspace',
      'welcome_back': 'Welcome back',
      'create_your_account': 'Create your account',
      'login': 'Login',
      'sign_up': 'Sign Up',
      'admin_code': 'Admin Code',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'email_address': 'Email Address',
      'password': 'Password',
      'login_hint': 'Use your registered email and password to continue.',
      'signup_hint': 'Your account will be used for orders, address saving, and faster checkout.',
      'continue_to_dashboard': 'Continue to Dashboard',
      'create_account': 'Create Account',
      'dont_have_account': "Don't have an account? Register now",
      'already_have_account': 'Already have an account? Login',
      'logout': 'Logout',
      'logout_confirm': 'Do you want to sign out from your account?',
      'cancel': 'Cancel',
      'logged_out': 'Logged out successfully',
      'fast_farm_delivery': 'Fast farm delivery',
      'smart_crop_title': 'Smart crop support\nfor every season',
      'smart_crop_subtitle':
          'Explore agricultural products curated for stronger roots, healthier plants, and smoother checkout.',
      'featured_products': 'Featured Products',
      'products_ready': 'products ready for quick ordering',
      'view_details': 'View Details',
      'payment_successful': 'Payment Successful',
      'payment_success_subtitle':
          'Your order has been placed successfully. Our team will review the delivery details and contact you shortly.',
      'next_step_delivery': 'Next step: delivery confirmation and team follow-up.',
      'back_to_marketplace': 'Back to Marketplace',
      'incoming_orders': 'Incoming Orders',
      'incoming_orders_subtitle':
          'Track customers, ordered products, and saved delivery addresses in one place.',
      'no_orders_found': 'No orders found yet.',
      'processing': 'Processing',
      'total_received': 'Total Received',
      'payment': 'Payment',
      'order_summary': 'Order Summary',
      'total_amount': 'Total Amount',
      'delivery': 'Delivery',
      'delivery_days': '3 - 4 Day',
      'delivery_address': 'Delivery Address',
      'add': 'Add',
      'change': 'Change',
      'add_address_before_payment': 'Add your address or current location before payment.',
      'current_location': 'Current Location',
      'saved_address': 'Saved Address',
      'pay_via_card': 'Pay via Card',
      'pay_now': 'Pay Now',
      'contact_seller': 'Contact Seller',
      'choose_delivery_location': 'Choose Delivery Location',
      'delivery_location_subtitle': 'Add the address where you want the order delivered.',
      'manual_address': 'Manual Address',
      'use_my_current_location': 'Use My Current Location',
      'fetching_location': 'Fetching Location...',
      'house_street_area': 'House / Street / Area',
      'landmark': 'Landmark',
      'city': 'City',
      'pincode': 'Pincode',
      'save_delivery_address': 'Save Delivery Address',
      'please_complete_address': 'Please complete the delivery address',
      'current_location_fetched': 'Current location fetched. You can save it now.',
      'enable_location_services': 'Please enable location services on your device',
      'location_permission_denied': 'Location permission was denied',
      'location_permission_denied_forever':
          'Location permission is permanently denied. Open app settings to enable it.',
      'settings': 'Settings',
      'profile': 'Profile',
      'no_email_found': 'No email found',
      'account_overview': 'Account Overview',
      'account_role': 'Account Role',
      'not_added_yet': 'Not added yet',
      'notifications': 'Notifications',
      'user_notifications_subtitle': 'Receive important updates about your orders and delivery flow.',
      'admin_notifications_subtitle': 'Receive important updates about new orders and customer activity.',
      'order_alerts': 'Order Alerts',
      'order_alerts_subtitle': 'Keep alerts on for newly placed orders and recent admin activity.',
      'location_access': 'Location Access',
      'location_access_subtitle': 'Keep location ready for faster address filling during checkout.',
      'app_language': 'App Language',
      'app_language_subtitle': 'Switch between Marathi and English anytime.',
      'go_to_admin_dashboard': 'Go to Admin Dashboard',
      'go_to_marketplace': 'Go to Marketplace',
      'back_to_welcome': 'Back to Welcome',
      'could_not_fetch_location': 'Could not fetch current location',
      'add_delivery_address_first': 'Please add your delivery address first',
      'current_location_fallback': 'Current Location',
      'farmer': 'Farmer',
      'hello_user': 'Hello {name}',
      'dashboard_subtitle': 'Your agri command center for shopping, crop support, farm updates, and faster buying decisions.',
      'quick_actions': 'Quick Actions',
      'shop_inputs': 'Shop Inputs',
      'shop_inputs_subtitle': 'Seeds, nutrition, and crop care',
      'my_cart': 'My Cart',
      'my_cart_subtitle': 'Checkout your current order',
      'order_history': 'Order History',
      'order_history_subtitle': 'Track your order status',
      'profile_short': 'Profile',
      'profile_short_subtitle': 'Language and account settings',
      'crop_feed': 'Crop Feed',
      'crop_feed_subtitle': 'Fresh product stories and updates',
      'why_app_better': 'Why This App Works Better',
      'field_ready_guidance': 'Field-ready guidance',
      'field_ready_guidance_subtitle': 'See solutions by crop health, soil nutrition, and stage of growth.',
      'faster_buying_decisions': 'Faster buying decisions',
      'faster_buying_decisions_subtitle': 'Compare trusted farm products in one place and move to checkout quickly.',
      'farmer_first_experience': 'Farmer-first experience',
      'farmer_first_experience_subtitle': 'Simple sections, local language support, and practical navigation.',
      'gallery_highlights': 'Gallery Highlights',
      'gallery_highlights_subtitle': 'Recent photos and videos from the gallery shown directly on the home screen.',
      'open_gallery': 'Open Gallery',
      'no_gallery_images': 'No gallery images yet',
      'no_gallery_images_subtitle': 'Photos and videos from the gallery will appear here once they are uploaded.',
      'video': 'Video',
      'photo': 'Photo',
      'cart_checkout_title': 'Cart and checkout',
      'cart_checkout_subtitle': 'Review your current order and move straight into payment when you are ready.',
      'checkout_center': 'Checkout center',
      'checkout_center_subtitle': 'Use this section to review products already chosen for your order.',
      'go_to_cart': 'Go to Cart',
      'home': 'Home',
      'shop': 'Shop',
      'agri_shop': 'Agri Shop',
      'agri_shop_subtitle': 'Discover crop solutions by need, compare trusted products, and move into checkout with less effort.',
      'farmer_first_shopping': 'Farmer-first shopping',
      'why_farmers_like_shop': 'Why farmers will like this shop',
      'why_farmers_like_shop_subtitle': 'A more guided experience inspired by modern agri-commerce apps.',
      'trusted_agri_products': 'Trusted agri products',
      'trusted_agri_products_subtitle': 'Crop nutrition and soil-support solutions arranged for quick discovery.',
      'farmer_friendly_flow': 'Farmer-friendly flow',
      'farmer_friendly_flow_subtitle': 'Simple browsing, clearer product cards, and quicker path to payment.',
      'built_for_repeat_buying': 'Built for repeat buying',
      'built_for_repeat_buying_subtitle': 'Move between product discovery, details, cart, and profile without friction.',
      'bio_fertilizers': 'Bio Fertilizers',
      'micronutrients': 'Micronutrients',
      'crop_boosters': 'Crop Boosters',
      'soil_care': 'Soil Care',
      'browse_solutions': 'Browse solutions',
      'request_quote': 'Request Quote',
      'please_login_view_cart': 'Please login to view your cart',
      'no_items_added_cart': 'No items added to your cart',
      'error_fetching_cart': 'Error fetching cart: {error}',
      'incomplete_form': 'Incomplete Form',
      'ok': 'OK',
      'please_fill_email_password': 'Please fill in email and password.',
      'please_fill_name_phone': 'Please fill in full name and phone number before signing up.',
      'please_enter_super_admin_code': 'Please enter the super admin code.',
      'please_enter_admin_code': 'Please enter the admin code.',
      'invalid_admin_code': 'Invalid admin code.',
      'invalid_super_admin_code': 'Invalid super admin code.',
      'super_admin_workspace': 'Super Admin Workspace',
      'super_admin_code': 'Super Admin Code',
      'database_error': 'Database Error: {error}',
      'invalid_email': 'Please enter a valid email address.',
      'incorrect_email_password': 'Incorrect email or password.',
      'email_registered_login': 'This email is already registered. Please log in instead.',
      'weak_password': 'Password should be at least 6 characters long.',
      'email_password_disabled': 'Email/password sign-in is not enabled in Firebase Auth.',
      'too_many_attempts': 'Too many attempts. Please wait a moment and try again.',
      'auth_failed': 'Authentication failed. Please try again.',
      'gallery_title': 'Gallery',
      'gallery_subtitle': 'Explore photos and videos shared from products, farms, and recent activity.',
      'no_memories_title': 'No memories shared yet',
      'no_memories_subtitle': 'Uploaded photos and videos will appear here once the team adds them.',
      'login_required': 'Login Required',
      'login_buy_product': 'Please login first to buy this product.',
      'login_add_to_cart': 'Please login first to add items to your cart.',
      'added_to_cart': '{name} added to cart!',
      'view_cart': 'View Cart',
      'failed_add_to_cart': 'Failed to add to cart: {error}',
      'tap_image_to_zoom': 'Tap image to zoom',
      'premium_crop_care': 'Premium Crop Care',
      'estimated_price': 'Estimated Price',
      'buy_now': 'Buy Now',
      'add_to_cart': 'Add to Cart',
      'address_mode_current': 'Current location selected',
      'address_mode_manual': 'Manual address selected',
      'revo_rhizal_name': 'REVO RHIZAL',
      'revo_rhizal_details': 'Mycorrhizal Bio Fertilizer',
      'revo_rhizal_description': 'Supports stronger root development and improves nutrient uptake for healthier crop growth.',
      'revo_micro_mix_name': 'REVO MICRO MIX',
      'revo_micro_mix_details': 'Mix Micronutrient Liquid',
      'revo_micro_mix_description': 'A balanced micronutrient blend designed to support plant vigor across multiple growth stages.',
      'revo_potash_name': 'REVO POTASH',
      'revo_potash_details': 'Potash Derived From Rhodophytes',
      'revo_potash_description': 'Helps improve crop quality, stress tolerance, and overall plant strength.',
    },
    'mr': {
      'app_name': 'रिव्हॉल्व अॅग्रो',
      'language': 'भाषा',
      'english': 'इंग्रजी',
      'marathi': 'मराठी',
      'grow_smarter_title': 'हुशार बना, निरोगी बना — आजची स्मार्ट शेती, उद्याचं यश',
      'grow_smarter_subtitle':
          'पीक काळजी उत्पादने शोधा, ऑर्डर पटकन द्या आणि तुमची शेती खरेदी एकाच सुंदर प्रवाहात सांभाळा.',
      'trusted_products': 'विश्वसनीय उत्पादने',
      'easy_checkout': 'सोपे चेकआउट',
      'continue': 'पुढे जा',
      'browse_products_directly': 'थेट उत्पादने पाहा',
      'choose_experience_title': 'तुमचा\nअनुभव निवडा',
      'choose_experience_subtitle':
          'शेतकरी आणि अॅडमिन यांना वेगळे डॅशबोर्ड, जलद कृती आणि अधिक सुटसुटीत खरेदी अनुभव मिळतो.',
      'user_login': 'युजर लॉगिन',
      'admin_login': 'अॅडमिन लॉगिन',
      'user_login_subtitle': 'उत्पादने पाहा, कार्ट व्यवस्थापित करा आणि डिलिव्हरी तपशीलांसह चेकआउट करा.',
      'admin_login_subtitle': 'आलेले ऑर्डर्स, ग्राहक पत्ते आणि एकूण ऑर्डर क्रियाकलाप पहा.',
      'super_admin_login': 'सुपर अॅडमिन लॉगिन',
      'super_admin_login_subtitle': 'सर्व अॅडमिन कार्यक्षमता आणि संपूर्ण सिस्टम सेटिंग्ज व्यवस्थापित करा.',
      'multilingual_support': 'बहुभाषिक शेती सहाय्य आणि जलद टीम समन्वयासाठी उपलब्ध.',
      'admin_workspace': 'अॅडमिन कार्यक्षेत्र',
      'farmer_workspace': 'शेतकरी कार्यक्षेत्र',
      'welcome_back': 'पुन्हा स्वागत आहे',
      'create_your_account': 'तुमचे खाते तयार करा',
      'login': 'लॉगिन',
      'sign_up': 'नोंदणी',
      'full_name': 'पूर्ण नाव',
      'phone_number': 'फोन नंबर',
      'email_address': 'ईमेल पत्ता',
      'password': 'पासवर्ड',
      'login_hint': 'पुढे जाण्यासाठी तुमचा नोंदणीकृत ईमेल आणि पासवर्ड वापरा.',
      'signup_hint': 'तुमचे खाते ऑर्डर, पत्ता जतन आणि जलद चेकआउटसाठी वापरले जाईल.',
      'continue_to_dashboard': 'डॅशबोर्डवर जा',
      'create_account': 'खाते तयार करा',
      'dont_have_account': 'खाते नाही? आत्ता नोंदणी करा',
      'already_have_account': 'आधीच खाते आहे? लॉगिन करा',
      'logout': 'लॉगआउट',
      'logout_confirm': 'तुम्हाला खात्यातून बाहेर पडायचे आहे का?',
      'cancel': 'रद्द करा',
      'logged_out': 'यशस्वीरित्या लॉगआउट झाले',
      'fast_farm_delivery': 'जलद शेत डिलिव्हरी',
      'smart_crop_title': 'प्रत्येक हंगामासाठी\nस्मार्ट पीक सहाय्य',
      'smart_crop_subtitle':
          'मजबूत मुळे, निरोगी रोपे आणि सोपे चेकआउट यासाठी निवडक शेती उत्पादने पाहा.',
      'featured_products': 'विशेष उत्पादने',
      'products_ready': 'उत्पादने झटपट ऑर्डरसाठी तयार',
      'view_details': 'तपशील पहा',
      'payment_successful': 'पेमेंट यशस्वी',
      'payment_success_subtitle':
          'तुमची ऑर्डर यशस्वीरित्या नोंदवली गेली आहे. आमची टीम डिलिव्हरी तपशील तपासून लवकरच संपर्क करेल.',
      'next_step_delivery': 'पुढील टप्पा: डिलिव्हरी पुष्टी आणि टीम संपर्क.',
      'back_to_marketplace': 'मार्केटप्लेसवर परत जा',
      'incoming_orders': 'आलेली ऑर्डर्स',
      'incoming_orders_subtitle':
          'ग्राहक, ऑर्डर केलेली उत्पादने आणि जतन केलेले डिलिव्हरी पत्ते एकाच ठिकाणी पहा.',
      'no_orders_found': 'अजून कोणतीही ऑर्डर नाही.',
      'processing': 'प्रक्रियेत',
      'total_received': 'एकूण प्राप्त',
      'payment': 'पेमेंट',
      'order_summary': 'ऑर्डर सारांश',
      'total_amount': 'एकूण रक्कम',
      'delivery': 'डिलिव्हरी',
      'delivery_days': '३ - ४ दिवस',
      'delivery_address': 'डिलिव्हरी पत्ता',
      'add': 'जोडा',
      'change': 'बदला',
      'add_address_before_payment': 'पेमेंटपूर्वी तुमचा पत्ता किंवा सद्य स्थान जोडा.',
      'current_location': 'सध्याचे स्थान',
      'saved_address': 'जतन केलेला पत्ता',
      'pay_via_card': 'कार्डद्वारे पेमेंट',
      'pay_now': 'आता पेमेंट करा',
      'contact_seller': 'विक्रेत्याशी संपर्क',
      'choose_delivery_location': 'डिलिव्हरी स्थान निवडा',
      'delivery_location_subtitle': 'तुमची ऑर्डर जिथे पोहोचवायची आहे तो पत्ता जोडा.',
      'manual_address': 'हस्तचलित पत्ता',
      'use_my_current_location': 'माझे सध्याचे स्थान वापरा',
      'fetching_location': 'स्थान घेत आहे...',
      'house_street_area': 'घर / रस्ता / परिसर',
      'landmark': 'ओळखचिन्ह',
      'city': 'शहर',
      'pincode': 'पिनकोड',
      'save_delivery_address': 'डिलिव्हरी पत्ता जतन करा',
      'please_complete_address': 'कृपया पूर्ण डिलिव्हरी पत्ता भरा',
      'current_location_fetched': 'सध्याचे स्थान मिळाले. आता जतन करा.',
      'enable_location_services': 'कृपया डिव्हाइसवरील स्थान सेवा सुरू करा',
      'location_permission_denied': 'स्थान परवानगी नाकारली गेली',
      'location_permission_denied_forever':
          'स्थान परवानगी कायमची नाकारली गेली आहे. सेटिंग्जमध्ये जाऊन ती सुरू करा.',
      'settings': 'सेटिंग्ज',
      'could_not_fetch_location': 'सध्याचे स्थान मिळवता आले नाही',
      'add_delivery_address_first': 'कृपया आधी डिलिव्हरी पत्ता जोडा',
      'current_location_fallback': 'सध्याचे स्थान',
      'farmer': 'शेतकरी',
      'hello_user': 'नमस्कार {name}',
      'dashboard_subtitle': 'खरेदी, पीक सहाय्य, शेतातील अपडेट्स आणि जलद निर्णयांसाठी तुमचे कृषी नियंत्रण केंद्र.',
      'quick_actions': 'जलद पर्याय',
      'shop_inputs': 'शेती इनपुट्स',
      'shop_inputs_subtitle': 'बियाणे, पोषण आणि पीक काळजी',
      'my_cart': 'माझे कार्ट',
      'my_cart_subtitle': 'तुमची सध्याची ऑर्डर तपासा',
      'order_history': 'ऑर्डर इतिहास',
      'order_history_subtitle': 'तुमच्या ऑर्डरची स्थिती ट्रॅक करा',
      'profile_short': 'प्रोफाइल',
      'profile_short_subtitle': 'भाषा आणि खाते सेटिंग्ज',
      'crop_feed': 'पीक फीड',
      'crop_feed_subtitle': 'नवीन उत्पादन कथा आणि अपडेट्स',
      'why_app_better': 'हे अॅप अधिक चांगले का आहे',
      'field_ready_guidance': 'शेतासाठी तयार मार्गदर्शन',
      'field_ready_guidance_subtitle': 'पीक आरोग्य, मातीचे पोषण आणि वाढीच्या टप्प्यानुसार उपाय पहा.',
      'faster_buying_decisions': 'जलद खरेदी निर्णय',
      'faster_buying_decisions_subtitle': 'विश्वासार्ह शेती उत्पादने एका ठिकाणी तुलना करा आणि लगेच पुढे जा.',
      'farmer_first_experience': 'शेतकरी-केंद्रित अनुभव',
      'farmer_first_experience_subtitle': 'सोपे विभाग, स्थानिक भाषा समर्थन आणि व्यवहार्य नेव्हिगेशन.',
      'gallery_highlights': 'गॅलरी हायलाइट्स',
      'gallery_highlights_subtitle': 'गॅलरीतील अलीकडील फोटो आणि व्हिडिओ थेट होम स्क्रीनवर.',
      'open_gallery': 'गॅलरी उघडा',
      'no_gallery_images': 'अजून गॅलरी प्रतिमा नाहीत',
      'no_gallery_images_subtitle': 'फोटो आणि व्हिडिओ अपलोड झाल्यावर येथे दिसतील.',
      'video': 'व्हिडिओ',
      'photo': 'फोटो',
      'cart_checkout_title': 'कार्ट आणि चेकआऊट',
      'cart_checkout_subtitle': 'तुमची सध्याची ऑर्डर तपासा आणि तयार झाल्यावर पेमेंट करा.',
      'checkout_center': 'चेकआऊट केंद्र',
      'checkout_center_subtitle': 'निवडलेली उत्पादने तपासण्यासाठी हा विभाग वापरा.',
      'go_to_cart': 'कार्टमध्ये जा',
      'home': 'होम',
      'shop': 'शॉप',
      'agri_shop': 'कृषी शॉप',
      'agri_shop_subtitle': 'गरजेनुसार उपाय शोधा, विश्वासार्ह उत्पादने तुलना करा आणि सहज चेकआऊट करा.',
      'farmer_first_shopping': 'शेतकरी-केंद्रित खरेदी',
      'why_farmers_like_shop': 'शेतकऱ्यांना हे शॉप का आवडेल',
      'why_farmers_like_shop_subtitle': 'आधुनिक कृषी-कॉमर्स अॅप्सपासून प्रेरित अधिक मार्गदर्शित अनुभव.',
      'trusted_agri_products': 'विश्वासार्ह कृषी उत्पादने',
      'trusted_agri_products_subtitle': 'पीक पोषण आणि मातीसाठी उपयुक्त उपाय जलद शोधासाठी मांडलेले आहेत.',
      'farmer_friendly_flow': 'शेतकरीसाठी सोपा प्रवाह',
      'farmer_friendly_flow_subtitle': 'सोपे ब्राउझिंग, स्पष्ट उत्पादन कार्ड्स आणि जलद पेमेंट मार्ग.',
      'built_for_repeat_buying': 'पुन्हा खरेदीसाठी योग्य',
      'built_for_repeat_buying_subtitle': 'उत्पादन, तपशील, कार्ट आणि प्रोफाइलमध्ये सहज जा.',
      'bio_fertilizers': 'जैव खते',
      'micronutrients': 'सूक्ष्म पोषकद्रव्ये',
      'crop_boosters': 'पीक बूस्टर्स',
      'soil_care': 'मातीची काळजी',
      'browse_solutions': 'उपाय पहा',
      'request_quote': 'कोट मागवा',
      'please_login_view_cart': 'कार्ट पाहण्यासाठी कृपया लॉगिन करा',
      'no_items_added_cart': 'तुमच्या कार्टमध्ये कोणतेही आयटम जोडलेले नाहीत',
      'error_fetching_cart': 'कार्ट मिळवताना त्रुटी: {error}',
      'incomplete_form': 'अपूर्ण फॉर्म',
      'ok': 'ठीक आहे',
      'please_fill_email_password': 'कृपया ईमेल आणि पासवर्ड भरा.',
      'please_fill_name_phone': 'नोंदणीपूर्वी कृपया पूर्ण नाव आणि फोन नंबर भरा.',
      'please_enter_super_admin_code': 'कृपया सुपर अॅडमिन कोड भरा.',
      'please_enter_admin_code': 'कृपया अॅडमिन कोड भरा.',
      'invalid_admin_code': 'अवैध अॅडमिन कोड.',
      'invalid_super_admin_code': 'अवैध सुपर अॅडमिन कोड.',
      'super_admin_workspace': 'सुपर अॅडमिन कार्यक्षेत्र',
      'super_admin_code': 'सुपर अॅडमिन कोड',
      'database_error': 'डेटाबेस त्रुटी: {error}',
      'invalid_email': 'कृपया वैध ईमेल पत्ता भरा.',
      'incorrect_email_password': 'ईमेल किंवा पासवर्ड चुकीचा आहे.',
      'email_registered_login': 'हा ईमेल आधीच नोंदणीकृत आहे. कृपया लॉगिन करा.',
      'weak_password': 'पासवर्ड किमान 6 अक्षरांचा असावा.',
      'email_password_disabled': 'Firebase Auth मध्ये ईमेल/पासवर्ड लॉगिन सुरू नाही.',
      'too_many_attempts': 'खूप प्रयत्न झाले. कृपया थोड्या वेळाने पुन्हा प्रयत्न करा.',
      'auth_failed': 'प्रमाणीकरण अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
    },
  };

  static const Map<String, Map<String, String>> _extraLocalizedValues = {
    'en': {
      'gallery_title': 'Gallery',
      'gallery_subtitle': 'Explore photos and videos shared from products, farms, and recent activity.',
      'no_memories_title': 'No memories shared yet',
      'no_memories_subtitle': 'Uploaded photos and videos will appear here once the team adds them.',
      'login_required': 'Login Required',
      'login_buy_product': 'Please login first to buy this product.',
      'login_add_to_cart': 'Please login first to add items to your cart.',
      'added_to_cart': '{name} added to cart!',
      'view_cart': 'View Cart',
      'failed_add_to_cart': 'Failed to add to cart: {error}',
      'tap_image_to_zoom': 'Tap image to zoom',
      'premium_crop_care': 'Premium Crop Care',
      'estimated_price': 'Estimated Price',
      'buy_now': 'Buy Now',
      'add_to_cart': 'Add to Cart',
      'address_mode_current': 'Current location selected',
      'address_mode_manual': 'Manual address selected',
      'revo_rhizal_name': 'REVO RHIZAL',
      'revo_rhizal_details': 'Mycorrhizal Bio Fertilizer',
      'revo_rhizal_description': 'Supports stronger root development and improves nutrient uptake for healthier crop growth.',
      'revo_micro_mix_name': 'REVO MICRO MIX',
      'revo_micro_mix_details': 'Mix Micronutrient Liquid',
      'revo_micro_mix_description': 'A balanced micronutrient blend designed to support plant vigor across multiple growth stages.',
      'revo_potash_name': 'REVO POTASH',
      'revo_potash_details': 'Potash Derived From Rhodophytes',
      'revo_potash_description': 'Helps improve crop quality, stress tolerance, and overall plant strength.',
    },
    'mr': {
      'gallery_title': 'गॅलरी',
      'gallery_subtitle': 'उत्पादने, शेत आणि अलीकडील क्रियाकलापांमधील फोटो आणि व्हिडिओ पहा.',
      'no_memories_title': 'अजून कोणतीही पोस्टर माहिती उपलब्ध नाही',
      'no_memories_subtitle': 'टीमने फोटो आणि व्हिडिओ जोडल्यावर ते येथे दिसतील.',
      'login_required': 'लॉगिन आवश्यक',
      'login_buy_product': 'हे उत्पादन खरेदी करण्यासाठी कृपया प्रथम लॉगिन करा.',
      'login_add_to_cart': 'कार्टमध्ये वस्तू जोडण्यासाठी कृपया प्रथम लॉगिन करा.',
      'added_to_cart': '{name} कार्टमध्ये जोडले गेले!',
      'view_cart': 'कार्ट पहा',
      'failed_add_to_cart': 'कार्टमध्ये जोडताना त्रुटी: {error}',
      'tap_image_to_zoom': 'झूम करण्यासाठी प्रतिमेवर टॅप करा',
      'premium_crop_care': 'प्रीमियम पीक काळजी',
      'estimated_price': 'अंदाजित किंमत',
      'buy_now': 'आत्ताच खरेदी करा',
      'add_to_cart': 'कार्टमध्ये जोडा',
      'address_mode_current': 'सध्याचे स्थान निवडले आहे',
      'address_mode_manual': 'हस्तचलित पत्ता निवडला आहे',
      'revo_rhizal_name': 'REVO RHIZAL',
      'revo_rhizal_details': 'मायकॉरायझल जैव खते',
      'revo_rhizal_description': 'मुळे अधिक मजबूत बनवते आणि निरोगी वाढीसाठी पोषकद्रव्यांचे शोषण सुधारते.',
      'revo_micro_mix_name': 'REVO MICRO MIX',
      'revo_micro_mix_details': 'मिश्र सूक्ष्म पोषक द्रव',
      'revo_micro_mix_description': 'वाढीच्या विविध टप्प्यांमध्ये पिकांच्या जोमासाठी संतुलित सूक्ष्म पोषक मिश्रण.',
      'revo_potash_name': 'REVO POTASH',
      'revo_potash_details': 'र्‍होडोफायट्सपासून मिळणारे पोटॅश',
      'revo_potash_description': 'पीक गुणवत्ता, ताणसहनशीलता आणि वनस्पतीची एकूण ताकद सुधारण्यास मदत करते.',
    },
  };

  String text(String key) {
    final languageCode = locale.languageCode;
    return _localizedValues[languageCode]?[key] ??
        _extraLocalizedValues[languageCode]?[key] ??
        _localizedValues['en']![key] ??
        _extraLocalizedValues['en']?[key] ??
        key;
  }

  String textWithArgs(String key, Map<String, String> args) {
    var value = text(key);
    args.forEach((placeholder, replacement) {
      value = value.replaceAll('{$placeholder}', replacement);
    });
    return value;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'mr'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}