// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpZ-_-oGCCYOjXGRehFqkJoH2ykvwXRYw',
    appId: '1:1053670723199:web:f9c36409e44fe42e0d794a',
    messagingSenderId: '1053670723199',
    projectId: 'revolveagro-9e98e',
    authDomain: 'revolveagro-9e98e.firebaseapp.com',
    storageBucket: 'revolveagro-9e98e.firebasestorage.app',
    measurementId: 'G-42508EXXR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Gh8BjVfdA5nRHCLxsKecl6s5w_l5xqg',
    appId: '1:1053670723199:android:91ad0d114639539f0d794a',
    messagingSenderId: '1053670723199',
    projectId: 'revolveagro-9e98e',
    storageBucket: 'revolveagro-9e98e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Ei2fbUWEyArHd_SK_ush9qrBo-oViTQ',
    appId: '1:1053670723199:ios:67ea434452dc05290d794a',
    messagingSenderId: '1053670723199',
    projectId: 'revolveagro-9e98e',
    storageBucket: 'revolveagro-9e98e.firebasestorage.app',
    iosBundleId: 'com.example.revolveagro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Ei2fbUWEyArHd_SK_ush9qrBo-oViTQ',
    appId: '1:1053670723199:ios:67ea434452dc05290d794a',
    messagingSenderId: '1053670723199',
    projectId: 'revolveagro-9e98e',
    storageBucket: 'revolveagro-9e98e.firebasestorage.app',
    iosBundleId: 'com.example.revolveagro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpZ-_-oGCCYOjXGRehFqkJoH2ykvwXRYw',
    appId: '1:1053670723199:web:32ad6450422275a90d794a',
    messagingSenderId: '1053670723199',
    projectId: 'revolveagro-9e98e',
    authDomain: 'revolveagro-9e98e.firebaseapp.com',
    storageBucket: 'revolveagro-9e98e.firebasestorage.app',
    measurementId: 'G-NNTXNT15LJ',
  );
}